const PDFDocument = require('pdfkit');

function generateDietPlanPDF(planData) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const buffers = [];

      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        const pdfData = Buffer.concat(buffers);
        resolve(pdfData.toString('base64'));
      });

      // Title
      doc.fontSize(20).font('Helvetica-Bold').fillColor('#5D3FD3').text('Inner Bloom - 7 Day Diet Plan', { align: 'center' });
      doc.moveDown();

      doc.fontSize(12).font('Helvetica').fillColor('#333333').text(`Personalized Diet Plan (Risk Level: ${planData.riskLevel})`, { align: 'center' });
      doc.moveDown(2);

      // Days loop
      if (planData.days && Array.isArray(planData.days)) {
        planData.days.forEach((dayObj) => {
          doc.fontSize(16).font('Helvetica-Bold').fillColor('#D8BFD8').text(`${dayObj.dayLabel || dayObj.day}`);
          doc.moveDown(0.5);

          doc.fontSize(12).font('Helvetica-Bold').fillColor('#000000').text('Breakfast: ', { continued: true })
             .font('Helvetica').text(dayObj.breakfast || '');
          doc.moveDown(0.5);

          doc.fontSize(12).font('Helvetica-Bold').text('Lunch: ', { continued: true })
             .font('Helvetica').text(dayObj.lunch || '');
          doc.moveDown(0.5);

          doc.fontSize(12).font('Helvetica-Bold').text('Dinner: ', { continued: true })
             .font('Helvetica').text(dayObj.dinner || '');
          doc.moveDown(0.5);

          doc.fontSize(12).font('Helvetica-Bold').text('Snacks: ', { continued: true })
             .font('Helvetica').text(dayObj.snacks || '');
          
          doc.moveDown(1.5);
        });
      }

      // Footer
      doc.fontSize(10).font('Helvetica-Oblique').fillColor('#888888').text('Generated by Inner Bloom AI. Please consult your physician for tailored medical advice.', 50, doc.page.height - 50, { align: 'center', width: doc.page.width - 100 });

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

module.exports = { generateDietPlanPDF };
